spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/sw
    username: root
    password: password123!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.MariaDBDialect

  data:
    mongodb:
      uri: mongodb://localhost:27017/test

logging:
  level:
    org.hibernate.sql: debug
